# Generated by Django 5.1.3 on 2024-12-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='user',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
            preserve_default=False,
        ),
    ]
