# Generated by Django 5.1.3 on 2024-12-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cartorder_options_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
